# Generated by Django 5.1.4 on 2024-12-18 16:22

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_menu_delete_guest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touch',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
